name = "HeaderArray"
uuid = "35342530-b88f-4ebc-9d14-598decc59a8e"
authors = ["Mitch Phillipson <mitch.phillipson@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.10"
DataFrames = "1.8.0"
OrderedCollections = "1.8.1"
